name: Ping

on:
  # schedule:
  #   - cron: '15 * * * *'
  push:
    branches:
      - pipeline

jobs:
  ping:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: ${{github.event.repository.homepagee}}
          max-attempts: 3
          retry-delay: 5s
      - name: Ping Failure
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ failure() }}
        with:
          severity: error
          text: ping failed
          details: ping failed :(
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
