name: Ping

on:
  push:
    branches:
      - pipeline

jobs:
  ping:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://full-stack-open-pokedex-production.up.railway\.app/
          max-attempts: 3 
          retry-delay: 5s 
          
  

