name: Pipeline

on:
  push:
    branches:
      - master
      - pipeline
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  # sample_deployment_pipeline:
  #   runs-on: ubuntu-20.04

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Setup node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '16.18.1'

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Lint
  #       run: npm run eslint

  #     - name: Build
  #       run: npm run build

  #     - name: Test
  #       run: npm run test

  #     - name: e2e tests
  #       uses: cypress-io/github-action@v5
  #       with:
  #         command: npm run test:e2e
  #         start: npm run start-prod
  #         wait-on: http://localhost:5000

  #     - name: Install Railway
  #       if: ${{ github.event_name == 'push' }}
  #       run: npm i -g @railway/cli

  #     - name: Deploy
  #       if: ${{ github.event_name == 'push' }}
  #       run: railway up
  #       env:
  #         RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

  # tag_release:
  #   needs: [sample_deployment_pipeline]
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Bump version and push tag
  #       if: ${{ github.event_name == 'push' }}
  #       uses: anothrNick/github-tag-action@1.64.0
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         DEFAULT_BUMP: patch

  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: joined messages
        env:
          JOINED_MESSAGES: ${{ join(github.event.commits.*.message, ',') }}
        run: echo "$JOINED_MESSAGES"
      - name: contains skip with hashtag
        env:
          CONTAINS_SKIP_HASHTAG: ${{ contains(join(github.event.commits.*.message, ', '), '#skip') }}
        run: echo "$CONTAINS_SKIP_HASHTAG"

      - name: contains skip
        env:
          CONTAINS_SKIP: ${{ contains(join(github.event.commits.*.message, ', '), 'skip') }}
        run: echo "$CONTAINS_SKIP"

